### ISSUE TITLE
Authorization Fails

### ISSUE THREAD

**Issue by Arul-NP** [qbsgroup/QBS.API.Example#1]
Dear there,
I have tested this code in BC 18 On Prem, The api call works perfectly in POSTMAN but when i apply same authorization in the request header it fails using this code.

in POSTMAN i have tried with inbuilt authentication using NTLM it works, instead if i try with Request Header it returns un authorized error.

Any help will be appreciated.

Regards,
 Arul

**Comment by ghost** [comment]
Hi Arul, these examples are shared as-is with no support or waranty. If you work for a QBS partner you may consider to put in a request for PTS services to work this out together with one of our teammembers.

Thank you so much for your interest in our examples.
